# Exercises Day 3 Philipp Wolf

In [1]:
import numpy as np

In [2]:
# a)
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
# b)
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
# c)
#c = np.flip(b)
c = np.arange(10,50)
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [5]:
# d)
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# e) 
e = np.array([1,2,0,0,4,0])
e_indices = np.where(e==0)[0]
e_indices

array([2, 3, 5], dtype=int64)

In [7]:
# f)
f = np.random.random((30))
mean_of_f = np.mean(f)
print(mean_of_f)

0.36259059251557396


In [10]:
# g)
g = np.ones((10,10))
g[1:-1,1:-1] = 0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# h)
h = np.ones((8,8),dtype=int)
h[0::2,1::2] = 0
h[1::2,0::2] = 0
print(h)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [17]:
# i)
i = np.array(([1,0],[0,1]),dtype=int)
i_tile = np.tile(i,(4,4))
print(i_tile)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [20]:
# j)
Z = np.arange(11)
Z[(Z>3) & (Z<8)] *= -1 
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [22]:
# k)
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.07897199 0.13701659 0.18182248 0.3847668  0.57800087 0.61951314
 0.76908699 0.80633163 0.81313341 0.905011  ]


In [36]:
# l)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

True


In [37]:
# m)
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.view(np.float32)
print(Z.dtype)

int32
float32


In [40]:
# n)
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]
